sudo: required
services:
  - docker

before_install:
  - docker build -t mstamos/docker-frontend -f Dockerfile.dev .

script:
  - docker run mstamos/docker-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-us-west-2-868371929475"
  bucket_path: "docker-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
